### ISSUE TITLE
Diff - retry missing from pipfile

### ISSUE THREAD

**Issue by jagonalez** [basset/basset#30]
- Pipfile is missing retry

**Comment by jagonalez** [comment]
fixed in #31

**Comment by emcniece** [comment]
I just ran into this while going through the setup steps, on `master` branch at commit ID `6ac4f423088a15bcdd940f3e64f11aab2d34ba38`.

Pip installs via `pip install -r requirements.txt`, and I was able to successfully build after amending to `diff/requirements.txt`. Does this file also need to have `retry` added to it?

**Comment by jagonalez** [comment]
Yes, `diff/requirements.txt` needs to have `retry`. I'll create a PR to add it in. Thank you for finding and reporting the issue.

If you use pipenv you can update the file by doing `pipenv lock -r > requirements.txt` from the `diff` folder. But I am creating a PR to add it in.
