### ISSUE TITLE
Feature request: Better error message for unsupported AWS regions with packer

### ISSUE THREAD

**Issue by jaller94** [basset/basset#43]
## Steps to reproduce
1. Follow the [AWS installation guide](https://basset.io/docs/aws) to the step where you run `packer build -var-file=./vars.json basset.json`.
   * The guide should also include a hint to load your AWS credentials into your environment. https://www.packer.io/docs/builders/amazon.html#authentication
2. Run `export AWS_DEFAULT_REGION="eu-west-1"` to default to Stockholm.
3. Run `packer build -var-file=./vars.json basset.json`.

## Expected
The script tells me that required features are not available in this AWS region.

## Actual
I got this fairly confusing output:
```
amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name: basset-app-1563973537
    amazon-ebs: Found Image ID: ami-88de55f6
==> amazon-ebs: Creating temporary keypair: packer_5d3857a2-e30c-9f01-6d88-0a27dfa3b2ce
==> amazon-ebs: Creating temporary security group for this instance: packer_5d3857bc-a0c8-ce9c-3600-402ab0be13a4
==> amazon-ebs: Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "Name": "Packer Builder"
==> amazon-ebs: Error launching source instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
==> amazon-ebs: 	status code: 400, request id: df32c9cc-1503-468a-823f-d98bd55f8710
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error launching source instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
	status code: 400, request id: df32c9cc-1503-468a-823f-d98bd55f8710

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error launching source instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
	status code: 400, request id: df32c9cc-1503-468a-823f-d98bd55f8710

==> Builds finished but no artifacts were created.
```

**Comment by jagonalez** [comment]
It looks like that region doesn't have`t2.micro` instances. You'll need to modify https://github.com/basset/basset/blob/master/infrastructure/packer/basset.json#L13 to be `t3.micro`

**Comment by jagonalez** [comment]
you'll run into the same issue when you use terraform here: https://github.com/basset/basset/blob/master/infrastructure/terraform/ec2.tf#L88 you'll need to update that as well

**Comment by jagonalez** [comment]
Closing as the error message comes directly from packer.

**Comment by jaller94** [comment]
What region have you used?
Maybe put that as a working option in the documentation?

**Comment by jagonalez** [comment]
I've used `us-west-2`, I can add that to the documentation. Are you still having issues with the zone?

**Comment by jaller94** [comment]
I thought so, because it was stating that `no matching Route53Zone found`.
But zone != region and now I figured out that the Ansible script wants me to manage/buy a domain name on AWS.
