### ISSUE TITLE
Hard-coded paths in infrastructure/playbook/roles/basset/tasks/main.yml

### ISSUE THREAD

**Issue by jaller94** [basset/basset#44]
## Steps to reproduce
1. Follow the [AWS installation guide](https://basset.io/docs/aws) to the step where you run `packer build -var-file=./vars.json basset.json`.
   * In a previous step the file `/home/jaller94/Git/github/basset/express/app.zip` got created on my system.
2. Configure your AWS credentials for Packer. (My default region is now `eu-west-1`.)
3. Run `packer build -var-file=./vars.json basset.json`.

## Expected
You adopt a basset on the Internet. (alias "The installation works.")

## Actual
I got the fatal error:
```
    amazon-ebs: TASK [basset : install basset] *************************************************
    amazon-ebs: task path: /home/jaller94/Git/github/basset/infrastructure/playbook/roles/basset/tasks/main.yml:148
    amazon-ebs: fatal: [default]: FAILED! => {"changed": false, "msg": "Could not find or access '/home/basset/dev/basset/express/app.zip' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
```
## Annotation
Yo, why is this hard-coded?

**Comment by jaller94** [comment]
Same goes for `/home/basset/dev/basset/basset.sql` in line 177.

**Comment by jagonalez** [comment]
it should be a relative directory or a configurable variable pointing to the direction app.zip is in.

But I want to change it to use this github repo and install it that way so you don't need to zip the directory on the local machine
