### ISSUE TITLE
basset.sql is missing

### ISSUE THREAD

**Issue by jaller94** [basset/basset#45]
The repo does not include the file `basset.sql`. The file is required in an Ansible playbook.

https://github.com/basset/basset/blob/741fb85ac9fdb55dc4d5691589862d1eaa9069f2/infrastructure/playbook/roles/basset/tasks/main.yml#L177

**Comment by jagonalez** [comment]
i'll add in something to deal with this better. a blank file should suffice if you want to get it working before i submit a PR for it
