### ISSUE TITLE
AWS region of the S3 screenshots bucket needs to support

### ISSUE THREAD

**Issue by jaller94** [basset/basset#46]
## Steps to reproduce
1. Follow https://basset.io/docs/aws
1.1. Create your screenshot bucket in `eu-west-1` (Ireland) or `us-east-1` (N. Virginia).
2. Get to the step to run `terraform plan`.

## Expected
The program terminates and tells you how to configure a different region for the Route53Zone.

## Actual 
The program terminates and leaves you to find out yourself how to configure a different zone and if that will work.
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.aws_availability_zones.current: Refreshing state...
data.aws_ami.basset_app: Refreshing state...
data.aws_route53_zone.basset_domain: Refreshing state...

Error: no matching Route53Zone found

  on route53.tf line 12, in data "aws_route53_zone" "basset_domain":
  12: data "aws_route53_zone" "basset_domain" {
```

**Comment by jagonalez** [comment]
Documentation could be a little more clear on this.

Step 7 is where the variables should be updated. Setting zone to whatever the domain hosted in AWS is. The assumption is there is a zone setup already in AWS.

https://github.com/basset/basset/blob/master/infrastructure/terraform/terraform.tfvars#L3

**Comment by jagonalez** [comment]
documentation updated in #49
