### ISSUE TITLE
Minimal repo or step by step tutorial how to set up selenium and basset-node

### ISSUE THREAD

**Issue by jaller94** [basset/basset#48]
As someone wanting to use basset in my projects, I struggle to set up the tool. A minimal repo where snapshots of a static website is done, would help me to understand it better than trying to extract selenium jest configurations from this repo.

I created a repo over here:
https://gitlab.com/jaller94/minimal-basset

Issues, PRs or just feedback on what is necessary and what not will be greatly appreciated.

**Comment by jagonalez** [comment]
sounds good @jaller94. 

It's on my list of things to do, but I should really make that list public.

You can also use puppeteer if that you're more comfortable with that.

I'm hoping to get to some of your other issues this weekend.

**Comment by jagonalez** [comment]
I've added a new repo with an example react app for generating snapshots with Basset. The setup is a little easier to do since it's using `jest-environment-selenium`.

https://github.com/basset/example-react-app
