### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by jaller94** [basset/basset#77]
`export` got misspelled
https://github.com/basset/basset/blob/771989b4908f9015a6ac86b6d094a4ebaaf6553b/infrastructure/terraform/userdata.tpl#L40

`environment variable` got misspelled two times
https://github.com/basset/basset/blob/771989b4908f9015a6ac86b6d094a4ebaaf6553b/diff/Makefile#L4-L8

**Comment by jagonalez** [comment]
fixed
