### ISSUE TITLE
Confused about AWS step 12 "Edit the Docker file to setup your environment variables"

### ISSUE THREAD

**Issue by jaller94** [basset/basset#78]
> 12. Edit the `Docker` file to setup your environment variables

Source: https://basset.io/docs/aws

I'm confused as to what this means.
* I assume you mean the `Dockerfile` file as there is no file called `Docker`.
* I assume you mean "set up" as the noun doesn't make sense here.
* I don't know what to edit in this file. There don't seem to be any comments or placeholders telling me what needs to be changed.

I skipped this step and things seem to be fine so far.

**Comment by jagonalez** [comment]
You can skip this step - the terraform HCL files take care of setting the proper environmental variables.
