### ISSUE TITLE
List of builds is empty when none of them were fully submitted

### ISSUE THREAD

**Issue by jaller94** [basset/basset#86]
## Steps to reproduce
1. Create an organization and a project.
2. Prepare to upload some snapshots.
3. Make the uploads begin, but have them fail during the upload. Technically speaking, you must call `/build/start` but not `/build/finish` on the API server.
4. Go to the list of builds in the webapp.

## Expected
The list shows me all builds you started.

## Actual
You have to finish at least one build for the list to populate.

**Comment by jagonalez** [comment]
This was addressed in #100 for now builds are being polled so new builds will appear and the status of the build will udpate as well.
