### ISSUE TITLE
Clicking a snapshot to hide the overlay is not intuitive

### ISSUE THREAD

**Issue by jaller94** [basset/basset#87]
When Basset detects changes and you get the page showing you "Original", "New" and "Difference", the last to tabs have the overlay on by default.

At that point, I was missing an unobstructed view onto the new snapshot.

Only by accident, I find out that clicking the snapshot toggles the overlay. I wish there had been a message or visual indicator on hover (like the cursor changing) to hint at this interaction.

**Comment by jagonalez** [comment]
I've made some changes in #93 to better show the interaction - the cursor now changes on hover and there's an icon button that will toggle the overlay.
